In [1]:
from pathlib import Path
import pandas as pd

In [2]:
csv_file = Path("/Users/katinkakurz/projects/Thesis/data/experiments/tagesschau_crawl/data/raw/tagesschau/tagesschau_2025-08-01_to_2025-10-31.csv")

df_first = pd.read_csv(csv_file)

print(df_first.shape)
print(df_first.columns.tolist())
df_first.head()

(3244, 42)
['sophoraId', 'externalId', 'title', 'date', 'tags', 'updateCheckUrl', 'content', 'tracking', 'topline', 'firstSentence', 'images', 'details', 'detailsweb', 'shareURL', 'geotags', 'regionId', 'regionIds', 'ressort', 'breakingNews', 'type', 'teaserImage.copyright', 'teaserImage.alttext', 'teaserImage.imageVariants.1x1-144', 'teaserImage.imageVariants.1x1-256', 'teaserImage.imageVariants.1x1-432', 'teaserImage.imageVariants.1x1-640', 'teaserImage.imageVariants.1x1-840', 'teaserImage.imageVariants.16x9-256', 'teaserImage.imageVariants.16x9-384', 'teaserImage.imageVariants.16x9-512', 'teaserImage.imageVariants.16x9-640', 'teaserImage.imageVariants.16x9-960', 'teaserImage.imageVariants.16x9-1280', 'teaserImage.imageVariants.16x9-1920', 'teaserImage.type', 'teaserImage.title', 'comments', 'brandingImage.title', 'brandingImage.copyright', 'brandingImage.alttext', 'brandingImage.imageVariants.original', 'brandingImage.type']

,sophoraId,externalId,title,date,tags,updateCheckUrl,content,tracking,topline,firstSentence,...,teaserImage.imageVariants.16x9-1280,teaserImage.imageVariants.16x9-1920,teaserImage.type,teaserImage.title,comments,brandingImage.title,brandingImage.copyright,brandingImage.alttext,brandingImage.imageVariants.original,brandingImage.type
0,afghanistan-flieger-pakistan-100,6463c06f-784f-4813-b7e2-d0fc2070c6fa,Deutschland holt zehn afghanische Familien aus...,2025-09-01T09:00:06.043+02:00,"[{'tag': 'Afghanistan'}, {'tag': 'Menschenrech...",https://www.tagesschau.de/api2u/afghanistan-fl...,[{'value': '<strong>Zehn afghanische Familien ...,[{'sid': 'app.ausland.afghanistan-flieger-paki...,Flieger auf dem Weg nach Hannover,Zehn afghanische Familien dürfen aus Pakistan ...,...,https://images.tagesschau.de/image/d87a08a6-d4...,https://images.tagesschau.de/image/d87a08a6-d4...,image,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,afghanistan-internet-104,80ab56f5-16bd-4343-994d-c202745c3362,Afghanistan ist wieder online,2025-10-01T18:30:21.655+02:00,"[{'tag': 'Afghanistan'}, {'tag': 'Internet'}]",https://www.tagesschau.de/api2u/afghanistan-in...,[{'value': '<strong>Handys und Internet funkti...,[{'sid': 'app.ausland.afghanistan-internet-104...,Nach Chaos im Land,Die Taliban begründeten den Ausfall mit techni...,...,https://images.tagesschau.de/image/da737e1d-cf...,https://images.tagesschau.de/image/da737e1d-cf...,image,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,aethiopien-deutsche-welle-korrespondenten-100,333b0442-121b-42f7-9395-379d426bbef2,Äthiopien suspendiert Deutsche-Welle-Journalisten,2025-10-24T19:37:10.246+02:00,"[{'tag': 'Äthiopien'}, {'tag': 'Deutsche Welle'}]",https://www.tagesschau.de/api2u/aethiopien-deu...,[{'value': '<strong>Die Deutsche Welle darf vo...,[{'sid': 'app.ausland.afrika.aethiopien-deutsc...,Medienbehörde EMA,Die Deutsche Welle darf vorerst nicht mehr dir...,...,https://images.tagesschau.de/image/ecca828c-42...,https://images.tagesschau.de/image/ecca828c-42...,image,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,aethiopien-kirche-einsturz-100,7cd86ce3-d711-42c7-9006-020ef1a7a713,Mindestens 30 Tote bei Einsturz von Baugerüst,2025-10-02T02:18:37.979+02:00,"[{'tag': 'Äthiopien'}, {'tag': 'Kirche'}, {'ta...",https://www.tagesschau.de/api2u/aethiopien-kir...,[{'value': '<strong>Viele Menschen befanden si...,[{'sid': 'app.ausland.afrika.aethiopien-kirche...,Äthiopien,"Obwohl die Kirche renoviert wurde, hatten sich...",...,https://images.tagesschau.de/image/52409cac-54...,https://images.tagesschau.de/image/52409cac-54...,image,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,agoa-usa-afrika-100,5068ef2d-48ce-4004-a227-48849a4c5e4b,Brechen afrikanische Exporte in die USA ein?,2025-09-30T15:28:43.132+02:00,"[{'tag': 'AGOA'}, {'tag': 'Afrika'}, {'tag': '...",https://www.tagesschau.de/api2u/agoa-usa-afrik...,[{'value': '<strong>Seit Jahrzehnten verkaufen...,[{'sid': 'app.ausland.afrika.agoa-usa-afrika-1...,Aus für Handelsabkommen AGOA,Seit Jahrzehnten verkaufen mehr als die Hälfte...,...,https://images.tagesschau.de/image/709ca8bf-6e...,https://images.tagesschau.de/image/709ca8bf-6e...,image,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
csv_file_2 = Path("/Users/katinkakurz/projects/Thesis/data/experiments/tagesschau_crawl/data/raw/tagesschau/tagesschau_2025-11-01_to_2026-01-31.csv")

df_second = pd.read_csv(csv_file_2)

print(df_second.shape)
print(df_second.columns.tolist())
df_second.head()

(3076, 42)
['sophoraId', 'externalId', 'title', 'date', 'tags', 'updateCheckUrl', 'content', 'tracking', 'topline', 'firstSentence', 'images', 'details', 'detailsweb', 'shareURL', 'geotags', 'regionId', 'regionIds', 'breakingNews', 'type', 'teaserImage.copyright', 'teaserImage.alttext', 'teaserImage.imageVariants.1x1-144', 'teaserImage.imageVariants.1x1-256', 'teaserImage.imageVariants.1x1-432', 'teaserImage.imageVariants.1x1-640', 'teaserImage.imageVariants.1x1-840', 'teaserImage.imageVariants.16x9-256', 'teaserImage.imageVariants.16x9-384', 'teaserImage.imageVariants.16x9-512', 'teaserImage.imageVariants.16x9-640', 'teaserImage.imageVariants.16x9-960', 'teaserImage.imageVariants.16x9-1280', 'teaserImage.imageVariants.16x9-1920', 'teaserImage.type', 'ressort', 'comments', 'teaserImage.title', 'brandingImage.title', 'brandingImage.copyright', 'brandingImage.alttext', 'brandingImage.imageVariants.original', 'brandingImage.type']

,sophoraId,externalId,title,date,tags,updateCheckUrl,content,tracking,topline,firstSentence,...,teaserImage.imageVariants.16x9-1920,teaserImage.type,ressort,comments,teaserImage.title,brandingImage.title,brandingImage.copyright,brandingImage.alttext,brandingImage.imageVariants.original,brandingImage.type
0,antifa-ost-100,b4e91255-f8f2-4593-88bc-94160ac4bed5,"Berlin überrascht von US-Entscheidung zu ""Anti...",2025-11-14T19:00:26.124+01:00,[{'tag': 'Antifa Ost'}],https://www.tagesschau.de/api2u/antifa-ost-100...,[{'value': '<strong>Die US-Regierung hat die d...,"[{'sid': 'app.antifa-ost-100', 'src': 'tagessc...",Als Terrorgruppe eingestuft,"Die US-Regierung hat die deutsche ""Antifa Ost""...",...,https://images.tagesschau.de/image/293d421f-8d...,image,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,neue-app-wichtige-fragen-100,36cdd982-bd26-4862-a254-21e332f4c9c1,Das ändert sich an der neuen tagesschau-App,2025-12-17T11:39:57.369+01:00,"[{'tag': 'FAQ'}, {'tag': 'tagesschau App'}, {'...",https://www.tagesschau.de/api2u/neue-app-wicht...,[{'value': '<strong>Bei der Neugestaltung der ...,[{'sid': 'app.app.neue-app-wichtige-fragen-100...,Fragen und Antworten,Die tagesschau-App wurde neu gestaltet. Hier b...,...,NaN,image,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,neue-tagesschau-app-106,5535ab9d-7e34-446c-be57-8e619516f9bd,Neue Version der tagesschau-App online,2025-12-01T11:31:18.585+01:00,"[{'tag': 'App'}, {'tag': 'tagesschau App'}]",https://www.tagesschau.de/api2u/neue-tagesscha...,[{'value': '<strong>Die tagesschau-App erschei...,"[{'sid': 'app.app.neue-tagesschau-app-106', 's...",Erweiterte Funktionen,Neue Version der tagesschau-App: Die Nutzenden...,...,https://images.tagesschau.de/image/f617b3b7-e2...,image,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,aegypten-parlament-wahl-100,246d96a3-ea7f-49af-b4b5-cfe26effbde9,"""Alle spielen diese Farce mit""",2025-11-10T12:57:55.522+01:00,"[{'tag': 'Ägypten'}, {'tag': 'Al-Sisi'}]",https://www.tagesschau.de/api2u/aegypten-parla...,[{'value': '<strong>Millionen Ägypter wählen h...,[{'sid': 'app.ausland.afrika.aegypten-parlamen...,Parlamentswahl in Ägypten,Das Regime von Präsident al-Sisi orchestriert ...,...,https://images.tagesschau.de/image/39039732-4a...,image,ausland,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,algerien-begnadigung-schriftsteller-100,baef2cf6-b617-4766-8eeb-6fb3e5f57b50,Algerien begnadigt Schriftsteller Sansal,2025-11-12T22:28:25.835+01:00,"[{'tag': 'Algerien'}, {'tag': 'Begnadigung'}, ...",https://www.tagesschau.de/api2u/algerien-begna...,[{'value': '<strong>Ein Jahr lang war der fran...,[{'sid': 'app.ausland.afrika.algerien-begnadig...,Nach Gesuch aus Deutschland,Ein Jahr lang war der französisch-algerische S...,...,https://images.tagesschau.de/image/75362518-04...,image,ausland,NaN,NaN,NaN,NaN,NaN,NaN,NaN